import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const TRANSLATIONS = {
  en: {
    // Header & Navigation
    backendOnline: 'Node.js + Express (MongoDB Connected)',
    backendConnecting: 'Connecting to API...',
    activeRole: 'Active Role',
    quickPreview: 'Quick Test Preview',
    farmerHub: 'Farmer Hub',
    marketplace: 'Marketplace',
    buyerDashboard: 'Buyer Dashboard',
    switchUser: 'Switch User / Log Out',
    liveRoute: 'Live Route',
    mandiLive: 'Mandi Prices Live',
    agriTechBadge: 'AgriTech 2.0',
    gridSubtitle: 'National Digital Agriculture Grid',

    // Branding Hero
    heroTaglineBadge: 'Direct Farm-to-Fork Connectivity',
    zeroMiddlemenBadge: 'Zero Middlemen',
    heroHeadline1: '“From Farm to You —',
    heroHeadline2: 'Fair Prices, Fresh Produce.”',
    heroNarrative: 'Connect directly with farmers, discover fresh produce, and eliminate unnecessary middlemen with AI-driven route coordination and guaranteed farm payouts.',
    benefit1Title: 'Direct Farmer Connection',
    benefit1Desc: 'Empowering farmers & FPOs with direct buyer negotiations.',
    benefit2Title: 'Fair & Transparent Pricing',
    benefit2Desc: 'Mandi benchmarking for honest rates for buyers & growers.',
    benefit3Title: 'Smart AI-Powered Logistics',
    benefit3Desc: 'Demand forecasting & cold-chain route optimization.',
    statFarmers: 'Farmers & FPOs',
    statBuyers: 'Bulk Buyers',
    statMiddlemanFee: '₹0 Middleman Fee',
    statPayouts: '100% Direct Payouts',
    statFleet: 'AI Fleet Active: 142 Farm Clusters Connected',

    // Role Selector
    loginAs: 'Login as',
    fillDemo: 'Fill Demo Credentials',
    roleFarmer: 'Farmer / FPO',
    roleFarmerSub: 'Sell harvest & crops',
    roleConsumer: 'Consumer',
    roleConsumerSub: 'Fresh daily farm produce',
    roleBuyer: 'Bulk Buyer',
    roleBuyerSub: 'Hotels, retail & exports',

    // Login Form
    welcomeBack: 'Welcome Back',
    loginSubheading: 'Login to continue to KisanDirect',
    identifierLabel: 'Mobile Number / Email',
    identifierPlaceholder: 'Enter your mobile number or email',
    passwordLabel: 'Password',
    passwordPlaceholder: 'Enter your password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot Password?',
    loginButton: 'Login',
    authenticating: 'Authenticating...',
    orDivider: 'OR',
    continueWithGoogle: 'Continue with Google',
    dontHaveAccount: "Don't have an account?",
    createAccount: 'Create Account',
    alreadyHaveAccount: 'Already have an account?',
    signInHere: 'Sign In here',
    trustProtected: 'Your data is securely protected.',
    empoweringAgri: 'Empowering Indian Agriculture',
    sslEncrypted: 'SSL 256-Bit Encrypted',

    // Registration Form
    joinKisanDirect: 'Create Account',
    joinSubtitle: "Join India's direct farm-to-table digital marketplace",
    fullName: 'Full Name',
    fullNamePlaceholder: 'e.g. Rameshwar Patel',
    farmName: 'Farm / FPO Name',
    farmNamePlaceholder: 'e.g. Patel Organic Farm',
    mobileNumber: 'Mobile Number',
    mobilePlaceholder: '10-digit mobile',
    emailOptional: 'Email (Optional)',
    emailRequired: 'Email Address',
    farmLocation: 'Farm Location',
    farmLocationPlaceholder: 'Village, District, State (e.g. Niphad, Nashik, MH)',
    deliveryLocation: 'Delivery Location',
    deliveryLocationPlaceholder: 'Apartment/Street, City, Pincode (e.g. Indiranagar, 560038)',
    businessName: 'Business Name',
    businessNamePlaceholder: 'e.g. TastyGreens Kitchens',
    contactPerson: 'Contact Person',
    contactPersonPlaceholder: 'e.g. Rajiv Mehra',
    businessType: 'Business Type',
    operatingLocation: 'Operating Location',
    operatingLocationPlaceholder: 'City, State & Hub Address (e.g. Navi Mumbai, MH)',
    createPassword: 'Create Password',
    createPasswordPlaceholder: 'Min 8 characters with numbers & symbols',
    agreeTermsText: "I agree to KisanDirect's",
    termsOfService: 'Terms of Service',
    andText: 'and',
    fairTradeCharter: 'Fair Trade Fair Price Charter',
    completeRegistration: 'Complete Registration',
    creatingAccount: 'Creating your account...',

    // Farmer Hub Dashboard
    farmerPortalBadge: 'Farmer & FPO Portal',
    farmerGreeting: 'Namaste',
    farmerBannerP1: 'Your farm listings are live on the National KisanDirect Grid. You currently have',
    farmerBannerP2: 'active crop lots available directly to consumers and bulk procurement buyers.',
    aiDemandTitle: 'AI Demand Forecast: High Wholesale Demand in Bengaluru & Mumbai',
    aiDemandDesc: 'Wholesale buyers have placed demand for 14.5 Tons of Hybrid Tomatoes & Red Onions at ₹32/kg (approx. 18% above the nearest APMC Mandi auction price). Click + Add New Crop Lot to list your harvest slot.',
    kpiActiveListings: 'Active Crop Listings',
    kpiDirectBuyers: 'Direct to 480+ bulk buyers',
    kpiDirectEarnings: 'Direct Earnings (This Month)',
    kpiBankPayout: '100% direct bank transfer payout',
    kpiMiddlemenSaved: 'Middlemen Fee Saved',
    kpiZeroCommission: '0% commission deducted by KisanDirect',
    catalogHeading: 'Your Harvest Catalog on Marketplace',
    catalogSubheading: 'Crops currently visible to verified consumers, restaurants, and wholesalers',
    addCropBtn: '+ Add New Crop Lot',
    noCropsYet: 'No crop lots listed yet',
    noCropsHelp: 'Click the button above to publish your first harvest!',
    availableStock: 'Available Stock',
    mandiBenchmark: 'Mandi Benchmark',
    hubLocation: 'Hub',

    // Consumer Marketplace
    marketplaceBadge: 'Fresh Marketplace',
    marketplaceHeroTag: 'Direct Farm-to-Fork Payout Guarantee',
    marketplaceHeroHeading: 'Direct from Farmers to your Kitchen Table 🥕',
    marketplaceHeroSub: 'Every fruit and vegetable on KisanDirect is harvested on-demand by verified farmers. 100% of your produce payment reaches the farmer directly without middleman markups.',
    cartButton: 'Cart',
    addToCartBtn: 'Add to Cart',
    addedToCartAlert: 'Added to cart!',
    viewCartLink: 'View Cart →',
    deliveringTo: 'Delivering to',

    // Cart Drawer
    cartDrawerTitle: 'Your Fresh Farm Cart',
    cartItemsDirect: 'items sourced directly',
    cartEmptyHeading: 'Your cart is empty',
    cartEmptyText: 'Add fresh farm-harvested fruits, vegetables, and greens to direct-order from Indian farmers.',
    exploreMarketBtn: 'Explore Farm Marketplace',
    zeroMiddlemenNotice: 'Zero middlemen cut: 100% of the produce price is disbursed directly to the harvesting farmers.',
    deliveryLocationLabel: 'Delivery Location',
    deliverySlotLabel: 'Harvest Delivery Slot',
    slotMorning: 'Tomorrow Morning (6 AM - 9 AM) — Fresh Morning Harvest',
    slotEvening: 'Tomorrow Evening (4 PM - 7 PM)',
    paymentModeHeading: 'Payment Mode',
    instantUpiBtn: '⚡ Instant UPI',
    codBtn: '💵 Cash on Delivery',
    produceSubtotalLabel: 'Produce Subtotal:',
    middlemenSavedLabel: 'Middlemen Commission:',
    savedLabel: 'Saved',
    coldDeliveryLabel: 'Direct Cold-Chain Delivery:',
    freeText: 'FREE',
    totalPayoutLabel: 'Total Direct Payout:',
    placeOrderCTA: 'Place Order',
    confirmingOrderState: 'Confirming Direct Order...',

    // Order Success Modal
    orderSuccessBadge: 'Farm Harvest Order Confirmed',
    orderSuccessTitle: 'Thank you for your order! 🎉',
    orderIdLabel: 'Order ID',
    directImpactHeading: '100% Direct Farmer Impact',
    directImpactText: 'is disbursed directly to our partner farmers with ₹0 middleman deductions. Fresh harvesting begins at sunrise!',
    deliverySlotReceipt: 'Delivery Slot:',
    deliveringToReceipt: 'Delivering To:',
    orderStatusReceipt: 'Order Status:',
    statusHarvesting: 'Harvesting at Farm',
    continueShoppingBtn: 'Continue Shopping',

    // Bulk Buyer Dashboard
    buyerPortalBadge: 'B2B Bulk Procurement',
    buyerGreeting: 'Welcome',
    buyerBannerDesc: 'Direct Farm Contract Procurements with AI Route Optimization & Guaranteed Mandi Benchmarked Pricing.',
    coldChainShipmentTitle: 'Active Cold-Chain Shipment #KD-7749 En Route',
    coldChainShipmentSub: 'Cluster: Nashik FPO → Central Warehouse Navi Mumbai • 4.2 Tons Grade-A Produce',
    optimalText: '4.2°C (Optimal)',
    etaText: 'ETA: 3 hrs 15 mins',
    procuredMonthLabel: 'Procured This Month',
    savingsVsTrad: '16.5% savings vs traditional wholesalers',
    activeContractsLabel: 'Active Forward Contracts',
    directFromClusters: 'Direct from Nashik, Pune & Ooty clusters',
    gstComplianceLabel: 'GST Invoice Compliance',
    autoTaxBills: 'Automated tax invoices & e-way bills',
    farmLotsHeading: 'Direct Farm Lots Available for Wholesale Procurement',
    liveFarmStockBadge: 'Live Farm Stock',
    farmLotsSub: 'Harvest lots published directly by verified Farmers & FPOs ready for wholesale pickup',
    procureLotBtn: 'Procure Lot',
    activeRFQsHeading: 'Your Active Wholesale RFQs',
    activeRFQsSub: 'Forward contracts and procurement requirements matched with farmer clusters',
    createRFQBtn: '+ Create New RFQ',
    noRFQsText: 'No active RFQs. Click the button above to publish your first wholesale requirement.',
    requirementLabel: 'Requirement',
    supplierLabel: 'Supplier',

    // Modals
    addCropModalTitle: 'List New Harvest Lot 🌾',
    addCropModalSub: 'Publish directly to 12,000+ Consumers & 480+ Bulk Buyers',
    cropVarietyLabel: 'Crop / Produce Variety',
    categoryLabel: 'Category',
    quantityLabel: 'Available Quantity',
    directPriceLabel: 'Direct Asking Price (₹/kg)',
    mandiPriceLabel: 'Nearest Mandi Price (₹/kg)',
    profitAdvantageNotice: 'You will earn',
    moreDirectNotice: 'more direct on KisanDirect compared to APMC middleman auction!',
    dispatchReadinessLabel: 'Dispatch Readiness',
    farmLocationLabel: 'Farm / Pickup Hub',
    cancelBtn: 'Cancel',
    publishCropBtn: 'Publish Crop Lot',

    createRFQModalTitle: 'Create Wholesale RFQ & Contract',
    createRFQModalSub: 'Procure directly from verified FPOs with AI route optimization',
    commodityRequiredLabel: 'Required Commodity / Crop Variety *',
    volumeRequiredLabel: 'Volume Required *',
    supplyFrequencyLabel: 'Supply Frequency',
    targetBuyingRateLabel: 'Target Buying Rate (₹/kg) *',
    deliveryHubLabel: 'Delivery Hub / Warehouse',
    coldChainTelemetryTitle: 'AI Cold-Chain Telemetry',
    coldChainTelemetrySub: 'Real-time truck temperature monitoring (2°C - 6°C)',
    publishRFQBtn: 'Publish Contract RFQ',

    // Extra Common Labels & Modals
    farmLabel: 'Farm',
    unitLabel: 'Unit',
    availableLabel: 'Available',
    locationLabel: 'Location',
    mandiRate: 'Mandi',
    removeCropLot: 'Remove crop lot',
    removeRFQ: 'Remove RFQ',
    newWholesaleRFQBtn: '+ New Wholesale RFQ',
    b2bBuyerTitle: 'Bulk Buyer / Institutional Procurement',
    directFarmLotsHeading: 'Direct Farm Lots Available for Wholesale Procurement',
    liveFarmStock: 'Live Farm Stock',
    availableLotsSub: 'Harvest lots published directly by verified Farmers & FPOs ready for wholesale pickup',
    procureLot: 'Procure Lot',
    activeWholesaleRFQs: 'Your Active Wholesale RFQs',
    wholesaleSub: 'Forward contracts and procurement requirements matched with farmer clusters',
    forgotPasswordTitle: 'Reset Your Password',
    forgotPasswordSub: 'Fast recovery for KisanDirect members',
    forgotPasswordInstruction: 'Enter your registered mobile number or email address, and we will send you an OTP to recover your account securely.',
    sendOtpBtn: 'Send OTP',
    resetDispatchedTitle: 'Reset Link / OTP Dispatched!',
    resetDispatchedDesc: 'We have sent a verification code to',
    checkMessages: 'Please check your messages or inbox to create your new password.',
    returnToLogin: 'Return to Login',
    categoryVegetables: 'Vegetables',
    categoryFruits: 'Fruits',
    categoryGrains: 'Grains & Cereals',
    categoryPulses: 'Pulses',
    categorySpices: 'Spices & Cash Crops',
    dispatchReadyNow: 'Ready for Immediate Dispatch',
    dispatch24h: 'Harvesting in 24 hrs',
    dispatch3d: 'Harvesting in 3 days',
    dispatchStanding: 'Standing Crop (Forward Contract)',
    lotsCount: 'Lots',
    tonsCount: 'Tons',
    contractsCount: 'Contracts',

    // Green Vegetable & Dynamic Farmer Marketplace
    filterAll: 'All Farm Produce',
    filterGreenVeg: '🥦 Green Vegetables',
    filterFarmerDirect: '🚜 Direct Farmer Lots',
    filterFruits: '🍎 Fruits & Grains',
    greenVegBroadcastTitle: 'Live Harvest: Fresh Green Vegetables Directly From Farmers 🥬',
    greenVegBroadcastSub: 'Every vegetable below is listed directly by verified Indian growers. When you order, fresh harvesting begins with 100% direct farmer payout.',
    farmerStockBadge: 'Direct Farm Lot',
    greenVegBadge: '100% Fresh Green Veg',
    quickAddVegChips: '🥬 Quick Pick Green Vegetables:',
    mrpSavingsText: 'Savings vs Supermarket',
    noProductsInCategory: 'No crops found in this filter. Check back shortly as farmers publish lots throughout the day!',
    liveFarmerCount: 'Farmers connected live',
  },

  hi: {
    // Header & Navigation
    backendOnline: 'नोड.जेएस + एक्सप्रेस (MongoDB सक्रिय)',
    backendConnecting: 'एपीआई से जुड़ रहा है...',
    activeRole: 'सक्रिय भूमिका',
    quickPreview: 'त्वरित डेमो परीक्षण',
    farmerHub: 'किसान हब',
    marketplace: 'ताज़ा मंडी',
    buyerDashboard: 'थोक डैशबोर्ड',
    switchUser: 'भूमिका बदलें / लॉग आउट',
    liveRoute: 'सक्रिय रूट',
    mandiLive: 'लाइव मंडी भाव सक्रिय',
    agriTechBadge: 'कृषि-टेक 2.0',
    gridSubtitle: 'राष्ट्रीय डिजिटल कृषि ग्रिड',

    // Branding Hero
    heroTaglineBadge: 'खेत से सीधे उपभोक्ता तक',
    zeroMiddlemenBadge: 'शून्य बिचौलिया कमीशन',
    heroHeadline1: '“खेत से सीधा आप तक —',
    heroHeadline2: 'सही दाम, ताज़ा उपज।”',
    heroNarrative: 'सीधे किसानों से जुड़ें, ताज़ा उपज पाएं और स्मार्ट AI लॉजिस्टिक्स एवं सीधी भुगतान गारंटी के साथ अनावश्यक बिचौलियों को पूरी तरह हटाएं।',
    benefit1Title: 'सीधा किसान संपर्क',
    benefit1Desc: 'किसानों और FPO को खरीदारों से सीधा जोड़कर 0% कमीशन पर पूरा लाभ।',
    benefit2Title: 'उचित व पारदर्शी मूल्य',
    benefit2Desc: 'मंडी भाव के अनुसार किसानों और खरीदारों दोनों के लिए पारदर्शी दाम।',
    benefit3Title: 'स्मार्ट AI लॉजिस्टिक्स',
    benefit3Desc: 'मांग पूर्वानुमान और कोल्ड-चेन द्वारा सुरक्षित व तेज़ परिवहन।',
    statFarmers: 'पंजीकृत किसान व FPO',
    statBuyers: 'थोक खरीदार व व्यापारी',
    statMiddlemanFee: '₹0 बिचौलिया कमीशन',
    statPayouts: '100% प्रत्यक्ष बैंक भुगतान',
    statFleet: 'सक्रिय AI फ्लीट: 142 कृषि क्लस्टर जुड़े हैं',

    // Role Selector
    loginAs: 'के रूप में लॉगिन करें',
    fillDemo: 'डेमो विवरण भरें',
    roleFarmer: 'किसान / FPO',
    roleFarmerSub: 'फसल व ताज़ा उपज बेचें',
    roleConsumer: 'उपभोक्ता',
    roleConsumerSub: 'ताज़ा घरेलू उपज खरीदें',
    roleBuyer: 'थोक खरीदार',
    roleBuyerSub: 'होटल, खुदरा व निर्यात हेतु',

    // Login Form
    welcomeBack: 'वापस स्वागत है',
    loginSubheading: 'किसानडायरेक्ट में आगे बढ़ने के लिए लॉगिन करें',
    identifierLabel: 'मोबाइल नंबर / ईमेल',
    identifierPlaceholder: 'अपना 10-अंकीय मोबाइल नंबर या ईमेल दर्ज करें',
    passwordLabel: 'पासवर्ड',
    passwordPlaceholder: 'अपना पासवर्ड दर्ज करें',
    rememberMe: 'मुझे याद रखें',
    forgotPassword: 'पासवर्ड भूल गए?',
    loginButton: 'लॉगिन करें',
    authenticating: 'सत्यापित किया जा रहा है...',
    orDivider: 'या',
    continueWithGoogle: 'गूगल (Google) से जारी रखें',
    dontHaveAccount: 'क्या आपका खाता नहीं है?',
    createAccount: 'नया खाता बनाएं',
    alreadyHaveAccount: 'पहले से खाता है?',
    signInHere: 'यहाँ लॉगिन करें',
    trustProtected: 'आपका डेटा 256-बिट एन्क्रिप्शन से पूरी तरह सुरक्षित है।',
    empoweringAgri: 'भारतीय कृषि और किसानों का सशक्तिकरण',
    sslEncrypted: 'SSL 256-बिट सुरक्षित',

    // Registration Form
    joinKisanDirect: 'नया खाता बनाएं',
    joinSubtitle: 'भारत के प्रत्यक्ष खेत-से-थाली डिजिटल मार्केटप्लेस से जुड़ें',
    fullName: 'पूरा नाम',
    fullNamePlaceholder: 'उदा. रामेश्वर पटेल',
    farmName: 'खेत / FPO संस्था का नाम',
    farmNamePlaceholder: 'उदा. पटेल ऑर्गेनिक फार्म',
    mobileNumber: 'मोबाइल नंबर',
    mobilePlaceholder: '10-अंकीय मोबाइल नंबर',
    emailOptional: 'ईमेल (वैकल्पिक)',
    emailRequired: 'ईमेल पता',
    farmLocation: 'खेत का स्थान',
    farmLocationPlaceholder: 'गाँव, जिला, राज्य (उदा. निफाड़, नासिक, महाराष्ट्र)',
    deliveryLocation: 'डिलीवरी का पता',
    deliveryLocationPlaceholder: 'मकान नं., सड़क, शहर, पिनकोड (उदा. 560038)',
    businessName: 'कंपनी / व्यापार का नाम',
    businessNamePlaceholder: 'उदा. टेस्टीग्रीन्स रेस्टोरेंट चेन',
    contactPerson: 'संपर्क व्यक्ति का नाम',
    contactPersonPlaceholder: 'उदा. राजीव मेहरा',
    businessType: 'व्यापार का प्रकार',
    operatingLocation: 'व्यापार का स्थान / हब',
    operatingLocationPlaceholder: 'शहर, राज्य (उदा. नवी मुंबई, महाराष्ट्र)',
    createPassword: 'नया पासवर्ड बनाएं',
    createPasswordPlaceholder: 'कम से कम 8 अक्षर (अंक व विशेष चिन्ह सहित)',
    agreeTermsText: 'मैं किसानडायरेक्ट की',
    termsOfService: 'सेवा शर्तों',
    andText: 'और',
    fairTradeCharter: 'उचित व्यापार किसान घोषणापत्र से सहमत हूँ',
    completeRegistration: 'पंजीकरण पूरा करें',
    creatingAccount: 'आपका खाता बनाया जा रहा है...',

    // Farmer Hub Dashboard
    farmerPortalBadge: 'किसान व FPO पोर्टल',
    farmerGreeting: 'नमस्ते',
    farmerBannerP1: 'आपकी फसल लिस्टिंग राष्ट्रीय किसानडायरेक्ट ग्रिड पर लाइव है। आज आपके पास',
    farmerBannerP2: 'सक्रिय फसल लॉट उपलब्ध हैं जो उपभोक्ताओं और थोक खरीदारों को दिखाई दे रहे हैं।',
    aiDemandTitle: 'AI मांग पूर्वानुमान: बेंगलुरु व मुंबई में भारी थोक मांग',
    aiDemandDesc: 'थोक खरीदारों ने हाइब्रिड टमाटर और लाल प्याज की 14.5 टन मांग ₹32/किग्रा पर दर्ज की है (निकटतम APMC मंडी नीलामी से लगभग 18% अधिक)। तुरंत + नया फसल लॉट जोड़ें पर क्लिक करें।',
    kpiActiveListings: 'सक्रिय फसल लिस्टिंग',
    kpiDirectBuyers: '480+ थोक खरीदारों से सीधा जुड़ाव',
    kpiDirectEarnings: 'प्रत्यक्ष कमाई (इस माह)',
    kpiBankPayout: '100% सीधा बैंक ट्रांसफर भुगतान',
    kpiMiddlemenSaved: 'बचाया गया बिचौलिया कमीशन',
    kpiZeroCommission: 'किसानडायरेक्ट द्वारा 0% कटौती',
    catalogHeading: 'मार्केटप्लेस पर आपकी फसल सूची',
    catalogSubheading: 'सत्यापित उपभोक्ताओं, होटलों और थोक व्यापारियों को दिखाई दे रही फसलें',
    addCropBtn: '+ नया फसल लॉट जोड़ें',
    noCropsYet: 'कोई फसल लॉट अभी सूचीबद्ध नहीं है',
    noCropsHelp: 'अपनी पहली फसल प्रकाशित करने के लिए ऊपर दिए बटन पर क्लिक करें!',
    availableStock: 'उपलब्ध स्टॉक',
    mandiBenchmark: 'मंडी बेंचमार्क भाव',
    hubLocation: 'हब',

    // Consumer Marketplace
    marketplaceBadge: 'ताज़ा कृषि मार्केटप्लेस',
    marketplaceHeroTag: 'प्रत्यक्ष खेत-से-थाली भुगतान गारंटी',
    marketplaceHeroHeading: 'किसानों से सीधे आपकी रसोई तक 🥕',
    marketplaceHeroSub: 'किसानडायरेक्ट पर प्रत्येक फल और सब्जी को सत्यापित किसानों द्वारा मांग पर ताज़ा काटा जाता है। आपका 100% भुगतान बिना किसी बिचौलिए के सीधे किसान तक पहुँचता है।',
    cartButton: 'कार्ट',
    addToCartBtn: 'कार्ट में जोड़ें',
    addedToCartAlert: 'कार्ट में जोड़ा गया!',
    viewCartLink: 'कार्ट देखें →',
    deliveringTo: 'डिलीवरी स्थान',

    // Cart Drawer
    cartDrawerTitle: 'आपका ताज़ा फार्म कार्ट',
    cartItemsDirect: 'सीधे खेतों से प्राप्त वस्तुएं',
    cartEmptyHeading: 'आपका कार्ट खाली है',
    cartEmptyText: 'भारतीय किसानों से सीधे ऑर्डर करने के लिए ताज़े फल, सब्जियाँ और अनाज जोड़ें।',
    exploreMarketBtn: 'मंडी में ताज़ा खरीदारी करें',
    zeroMiddlemenNotice: 'शून्य बिचौलिया कटौती: उपज मूल्य का 100% सीधे फसल काटने वाले किसानों के बैंक खाते में जाता है।',
    deliveryLocationLabel: 'डिलीवरी का पता',
    deliverySlotLabel: 'ताज़ा डिलीवरी समय स्लॉट',
    slotMorning: 'कल सुबह (6 AM - 9 AM) — सुबह की ताज़ा कटाई',
    slotEvening: 'कल शाम (4 PM - 7 PM)',
    paymentModeHeading: 'भुगतान का तरीका',
    instantUpiBtn: '⚡ तत्काल UPI',
    codBtn: '💵 कैश ऑन डिलीवरी',
    produceSubtotalLabel: 'उपज उप-योग:',
    middlemenSavedLabel: 'बचाया गया कमीशन:',
    savedLabel: 'बचत',
    coldDeliveryLabel: 'प्रत्यक्ष कोल्ड-चेन डिलीवरी:',
    freeText: 'मुफ़्त',
    totalPayoutLabel: 'कुल प्रत्यक्ष भुगतान:',
    placeOrderCTA: 'ऑर्डर करें',
    confirmingOrderState: 'ऑर्डर पक्का किया जा रहा है...',

    // Order Success Modal
    orderSuccessBadge: 'खेत से फसल ऑर्डर पुष्ट हुआ',
    orderSuccessTitle: 'आपके ऑर्डर के लिए धन्यवाद! 🎉',
    orderIdLabel: 'ऑर्डर आईडी',
    directImpactHeading: '100% प्रत्यक्ष किसान लाभ',
    directImpactText: 'का भुगतान बिना किसी बिचौलिए के सीधे हमारे किसान साझेदारों को किया गया है। ताज़ा कटाई सूर्योदय पर शुरू होगी!',
    deliverySlotReceipt: 'डिलीवरी समय:',
    deliveringToReceipt: 'डिलीवरी का पता:',
    orderStatusReceipt: 'ऑर्डर स्थिति:',
    statusHarvesting: 'खेत में ताज़ा कटाई जारी',
    continueShoppingBtn: 'खरीदारी जारी रखें',

    // Bulk Buyer Dashboard
    buyerPortalBadge: 'B2B थोक खरीद पोर्टल',
    buyerGreeting: 'स्वागत है',
    buyerBannerDesc: 'AI रूट अनुकूलन और गारंटीकृत मंडी-बेंचमार्क मूल्य निर्धारण के साथ प्रत्यक्ष फार्म अनुबंध खरीद।',
    coldChainShipmentTitle: 'सक्रिय कोल्ड-चेन खेप #KD-7749 मार्ग में है',
    coldChainShipmentSub: 'क्लस्टर: नासिक FPO → केंद्रीय गोदाम नवी मुंबई • 4.2 टन ग्रेड-A उपज',
    optimalText: '4.2°C (अनुकूलतम तापमान)',
    etaText: 'आगमन: 3 घंटे 15 मिनट',
    procuredMonthLabel: 'इस माह कुल खरीद',
    savingsVsTrad: 'पारंपरिक थोक मंडियों की तुलना में 16.5% बचत',
    activeContractsLabel: 'सक्रिय फॉरवर्ड अनुबंध',
    directFromClusters: 'सीधे नासिक, पुणे और ऊटी क्लस्टरों से',
    gstComplianceLabel: 'GST इनवॉइस अनुपालन',
    autoTaxBills: 'स्वचालित कर इनवॉइस और ई-वे बिल',
    farmLotsHeading: 'थोक खरीद हेतु उपलब्ध लाइव फार्म लॉट',
    liveFarmStockBadge: 'लाइव फार्म स्टॉक',
    farmLotsSub: 'सत्यापित किसानों और FPOs द्वारा थोक उठान हेतु तैयार फसल लॉट',
    procureLotBtn: 'लॉट खरीदें',
    activeRFQsHeading: 'आपकी सक्रिय थोक RFQ सूची',
    activeRFQsSub: 'किसान क्लस्टरों से जुड़े फॉरवर्ड अनुबंध और खरीद आवश्यकताएं',
    createRFQBtn: '+ नया थोक RFQ बनाएं',
    noRFQsText: 'कोई सक्रिय RFQ नहीं है। पहली थोक खरीद आवश्यकता पोस्ट करने के लिए ऊपर क्लिक करें।',
    requirementLabel: 'आवश्यकता',
    supplierLabel: 'आपूर्तिकर्ता',

    // Modals
    addCropModalTitle: 'नया फसल लॉट सूचीबद्ध करें 🌾',
    addCropModalSub: '12,000+ उपभोक्ताओं और 480+ थोक खरीदारों को सीधा दिखाएं',
    cropVarietyLabel: 'फसल / उपज का नाम',
    categoryLabel: 'श्रेणी',
    quantityLabel: 'उपलब्ध मात्रा',
    directPriceLabel: 'सीधा विक्रय मूल्य (₹/किग्रा)',
    mandiPriceLabel: 'निकटतम मंडी भाव (₹/किग्रा)',
    profitAdvantageNotice: 'आप कमाएंगे',
    moreDirectNotice: 'अधिक सीधा मुनाफा APMC बिचौलिया नीलामी की तुलना में!',
    dispatchReadinessLabel: 'डिलीवरी तैयारी स्थिति',
    farmLocationLabel: 'खेत / उठान हब का स्थान',
    cancelBtn: 'रद्द करें',
    publishCropBtn: 'फसल प्रकाशित करें',

    createRFQModalTitle: 'थोक RFQ एवं फॉरवर्ड अनुबंध बनाएं',
    createRFQModalSub: 'सत्यापित FPOs से सीधे थोक माल खरीदें (AI मार्ग अनुकूलन सहित)',
    commodityRequiredLabel: 'आवश्यक फसल / उपज किस्म *',
    volumeRequiredLabel: 'आवश्यक मात्रा *',
    supplyFrequencyLabel: 'आपूर्ति आवृत्ति',
    targetBuyingRateLabel: 'लक्षित खरीद दर (₹/किग्रा) *',
    deliveryHubLabel: 'डिलीवरी गोदाम / कोल्ड हब',
    coldChainTelemetryTitle: 'AI कोल्ड-चेन निगरानी',
    coldChainTelemetrySub: 'रीयल-टाइम तापमान मॉनिटरिंग (2°C - 6°C)',
    publishRFQBtn: 'थोक अनुबंध प्रकाशित करें',

    // Extra Common Labels & Modals
    farmLabel: 'खेत',
    unitLabel: 'इकाई',
    availableLabel: 'उपलब्ध',
    locationLabel: 'स्थान',
    mandiRate: 'मंडी भाव',
    removeCropLot: 'फसल लॉट हटाएं',
    removeRFQ: 'RFQ हटाएं',
    newWholesaleRFQBtn: '+ नया थोक RFQ',
    b2bBuyerTitle: 'थोक खरीदार / संस्थागत खरीद',
    directFarmLotsHeading: 'थोक खरीद हेतु उपलब्ध लाइव फार्म लॉट',
    liveFarmStock: 'लाइव फार्म स्टॉक',
    availableLotsSub: 'सत्यापित किसानों और FPOs द्वारा थोक उठान हेतु तैयार फसल लॉट',
    procureLot: 'लॉट खरीदें',
    activeWholesaleRFQs: 'आपकी सक्रिय थोक RFQs',
    wholesaleSub: 'किसान क्लस्टरों से जुड़े फॉरवर्ड अनुबंध और खरीद आवश्यकताएं',
    forgotPasswordTitle: 'अपना पासवर्ड रीसेट करें',
    forgotPasswordSub: 'किसानडायरेक्ट सदस्यों के लिए त्वरित रिकवरी',
    forgotPasswordInstruction: 'अपना पंजीकृत मोबाइल नंबर या ईमेल पता दर्ज करें, हम खाता सुरक्षित रूप से पुनर्प्राप्त करने के लिए ओटीपी भेजेंगे।',
    sendOtpBtn: 'OTP भेजें',
    resetDispatchedTitle: 'रीसेट लिंक / OTP भेज दिया गया!',
    resetDispatchedDesc: 'हमने सत्यापन कोड भेजा है:',
    checkMessages: 'कृपया नया पासवर्ड बनाने के लिए अपने संदेश या इनबॉक्स की जाँच करें।',
    returnToLogin: 'लॉगिन पर वापस जाएँ',
    categoryVegetables: 'सब्जियाँ',
    categoryFruits: 'फल',
    categoryGrains: 'अनाज व दलहन',
    categoryPulses: 'दालें',
    categorySpices: 'मसाले व नकदी फसलें',
    dispatchReadyNow: 'तुरंत उठान के लिए तैयार',
    dispatch24h: '24 घंटे में कटाई',
    dispatch3d: '3 दिनों में कटाई',
    dispatchStanding: 'खड़ी फसल (फॉरवर्ड अनुबंध)',
    lotsCount: 'लॉट',
    tonsCount: 'टन',
    contractsCount: 'अनुबंध',

    // Green Vegetable & Dynamic Farmer Marketplace
    filterAll: 'सभी कृषि उत्पाद',
    filterGreenVeg: '🥦 हरी सब्जियाँ',
    filterFarmerDirect: '🚜 सीधे किसान की फसल',
    filterFruits: '🍎 फल व अनाज',
    greenVegBroadcastTitle: 'किसानों से सीधा: ताज़ी हरी सब्जियाँ व खेत की फसलें 🥬',
    greenVegBroadcastSub: 'नीचे दी गई प्रत्येक हरी सब्जी सीधे सत्यापित किसानों द्वारा सूचीबद्ध की गई है। ऑर्डर करने पर तुरंत ताज़ा कटाई और 100% सीधा किसान भुगतान।',
    farmerStockBadge: 'सीधा खेत से',
    greenVegBadge: '100% ताज़ी हरी सब्जी',
    quickAddVegChips: '🥬 त्वरित हरी सब्जी चुनें:',
    mrpSavingsText: 'सुपरमार्केट की तुलना में बचत',
    noProductsInCategory: 'इस श्रेणी में अभी कोई फसल नहीं है। किसान दिनभर नए लॉट प्रकाशित करते हैं!',
    liveFarmerCount: 'किसान लाइव जुड़े हैं',
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('kisandirect_lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('kisandirect_lang', language);
    document.documentElement.lang = language;
  }, [language]);

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'en' ? 'hi' : 'en'));
  };

  const t = (key) => {
    const dict = TRANSLATIONS[language] || TRANSLATIONS.en;
    return dict[key] || TRANSLATIONS.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    const lang = typeof window !== 'undefined' ? localStorage.getItem('kisandirect_lang') || 'en' : 'en';
    return {
      language: lang,
      setLanguage: () => {},
      toggleLanguage: () => {},
      t: (key) => {
        const dict = TRANSLATIONS[lang] || TRANSLATIONS.en;
        return dict[key] || TRANSLATIONS.en[key] || key;
      },
    };
  }
  return context;
};
